sudo: false
language: c
dist: trusty
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
install:
  - mkdir ninjadir
  - export PATH="`pwd`/ninjadir:${PATH}"
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip -d ninjadir
  - pip3 install --user meson
compiler:
  - gcc
  - clang
script:
  - meson build
  - ninja -C build test
